### ISSUE TITLE
Ziek man! Lekker bezig

### ISSUE THREAD

**Issue by Razpudding** [yoeripasmans/real-time-web#1]
Heb je wel de rechten op die audio? En is dit bijv. gebaseerd op die ene tutorial van Wes Bos? Want dan mag dat er wel bij in de credits.

**Comment by yoeripasmans** [comment]
Audio zijn verschillende samples uit gratis sample packs, daarnaast is het Web Audio gedeelte de applicatie vooral gebaseerd op https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API.

**Comment by Razpudding** [comment]
Even better 👍
